// golem-tables <out.inc>
//
// Writes the driver's note tables (RGBDS syntax) from the reference player's, so that both
// always agree: NotePeriods (dw, notes 1..72) and NoiseNr43 (db, notes 1..72, width bit clear).

#include "golem/notes.h"

#include <cstdio>

int main(
    int argc,
    char** argv)
{
    if (argc != 2) {
        std::fprintf(stderr, "usage: golem-tables <out.inc>\n");
        return 2;
    }
    std::FILE* out = std::fopen(argv[1], "w");
    if (out == nullptr) {
        std::fprintf(stderr, "cannot write %s\n", argv[1]);
        return 1;
    }
    std::fprintf(out, "; Generated by golem-tables from core/src/notes.cpp. Do not edit.\n\n");
    std::fprintf(out, "NotePeriods:: ; Period for notes 1..72 (C-2..B-7).\n");
    for (int note = golem::kFirstNote; note <= golem::kLastNote; ++note) {
        std::fprintf(out, "\tdw $%03X\n", golem::note_period(static_cast<std::uint8_t>(note)));
    }
    std::fprintf(out, "\nNoiseNr43:: ; NR43 shift and divider for notes 1..72.\n");
    for (int note = golem::kFirstNote; note <= golem::kLastNote; ++note) {
        std::fprintf(out, "\tdb $%02X\n", golem::noise_nr43(static_cast<std::uint8_t>(note)));
    }
    return std::fclose(out) == 0 ? 0 : 1;
}
